Repository spiral/roadrunner-binary, pull requests merged in 2021-08, with the labels that each got.

#86 fix(config): add `debug` pool key to the `.rr.yaml`
  .rr.yaml
  CHANGELOG.md
Labels: Bug: regression bugs

#87 feat(plugin): add jobs plugin (alpha)
  .github/dependabot.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .gitignore
  .rr-sample-bench.yaml
  .rr.yaml
  CHANGELOG.md
  go.mod
  go.sum
  internal/cli/workers/render.go
  internal/container/plugins.go
Labels: A-module, C-enhancement

#88 feat(pre-release) `v2.4.0-beta.1` pre-release
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .gitignore
  .golangci.yml
  .rr-sample-bench.yaml
  .rr-with-temporal.yaml
  .rr.yaml
  CHANGELOG.md
  Makefile.docker
  go.mod
  go.sum
  internal/cli/workers/command.go
  internal/cli/workers/render.go
Labels: C-enhancement

#89 ci(ghcr, docker): support github packages
  .github/workflows/release.yml
Labels: A-ci, C-enhancement

#91 feat(pre-release): `v2.4.0-rc.1`
  .gitignore
  .rr-sample-bench-jobs.yaml
  CHANGELOG.md
  go.mod
  go.sum
  internal/cli/workers/render.go
  internal/container/plugins.go
Labels: C-enhancement
