Repository spiral/roadrunner-binary, pull requests merged in 2021-03, with the labels that each got.

#11 feature(cli): graceful shutdown with grace period
  .rr.yaml
  CHANGELOG.md
  cli/plugins.go
  cli/root.go
  cli/serve.go
  go.mod
  main.go
Labels: C-enhancement, P-High

#13 ⚡ feat(release): release v2.0.1
  .github/workflows/build.yaml
  .github/workflows/release.yml
  .rr.yaml
  CHANGELOG.md
  cli/root.go
  go.mod
  go.sum
Labels: C-enhancement

#15 config(desc): http.ssl.root_ca is optional now (description updated)
  .rr.yaml
Labels: A-docs

#17 💻 update(CI): update golangci-lint version in the CI
  .github/workflows/build.yaml
Labels: A-ci

#18 🖥 update(CI): support for the M1 (macOS, arm64) releases
  .github/workflows/release.yml
  CHANGELOG.md
Labels: A-ci, beta-nominated, stable-nominated

#20 update(dockerfile): add support for the `linux/arm64` platform, bump GO version
  .github/workflows/release.yml
  CHANGELOG.md
  Dockerfile
Labels: A-ci, beta-nominated, stable-nominated

#23 feat(env): add dotenv file support
  CHANGELOG.md
  cli/root.go
  go.mod
  go.sum
Labels: A-other, C-enhancement, beta-nominated

#24 refactor(app): Deep application refactoring
  .dockerignore
  .editorconfig
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/build.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .gitignore
  .golangci.yml
  CHANGELOG.md
  Dockerfile
  Makefile.docker
  README.md
  cli/plugins.go
  cli/reset.go
  cli/root.go
  cli/serve.go
  cli/version.go
  cli/workers.go
  cmd/rr/command_test.go
  cmd/rr/main.go
  go.mod
  go.sum
  internal/cli/reset/command.go
  internal/cli/reset/command_test.go
  internal/cli/root.go
  internal/cli/root_test.go
  internal/cli/serve/command.go
  internal/cli/serve/command_test.go
  internal/cli/workers/command.go
  internal/cli/workers/command_test.go
  internal/container/config.go
  internal/container/config_test.go
  internal/container/container.go
  internal/container/container_test.go
  internal/container/plugins.go
  internal/container/plugins_test.go
  internal/debug/server.go
  internal/debug/server_test.go
  internal/meta/meta.go
  internal/meta/meta_test.go
  internal/rpc/client.go
  internal/rpc/client_test.go
  main.go
  plugins.go
Labels: A-ci, A-other, A-tests, C-enhancement

#28 fix(endure): use error log level by default
  internal/container/config.go
  internal/container/config_test.go
Labels: A-other

#30 feat(configurer): Add ability to provide global configuration options via the Config plugin
  CHANGELOG.md
  Dockerfile
  Makefile
  codecov.yml
  go.mod
  go.sum
  internal/cli/serve/command.go
Labels: A-module, C-enhancement, beta-nominated, stable-nominated
