Repository spiral/roadrunner-binary, pull requests merged in 2021-09, with the labels that each got.

#92 feat(release): `v2.4.0`
  .rr-sample-bench-jobs.yaml
  .rr-sample-bench.yaml
  .rr-with-temporal.yaml
  .rr.yaml
  CHANGELOG.md
  dev/.rr-docker.yaml
  dev/Dockerfile.local
  dev/Makefile
  dev/README.md
  dev/composer.json
  dev/docker-compose.yml
  dev/psr-worker.php
  go.mod
  go.sum
  internal/container/plugins.go
Labels: A-other, C-enhancement

#94 fix(jobs): fix jobs stats fields in the `workers -i` mode
  go.mod
  go.sum
  internal/cli/workers/render.go
Labels: A-other, Bug: regression bugs, P-High, beta-nominated, stable-nominated

#96 feat(release): `v2.4.2`
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement

#95 upd(config): update `.rr.yaml` reference configuration
  .rr.yaml
  .vscode/settings.json
  CHANGELOG.md
Labels: A-docs, C-enhancement

#99 feat(plugins): add `roadrunner-plugins` repository
  go.mod
  go.sum
  internal/cli/reset/command.go
  internal/cli/reset/command_test.go
  internal/cli/root.go
  internal/cli/serve/command.go
  internal/cli/serve/command_test.go
  internal/cli/workers/command.go
  internal/cli/workers/command_test.go
  internal/cli/workers/render.go
  internal/container/config.go
  internal/container/config_test.go
  internal/container/plugins.go
  internal/rpc/client.go
  internal/rpc/client_test.go
Labels: A-module, C-enhancement

#100 feat(pre-release) `v2.5.0` alpha pre-release
  .gitignore
  .rr.yaml
  CHANGELOG.md
  go.mod
  go.sum
  internal/container/plugins.go
Labels: C-enhancement

#102 update(ci): Version value extracting improved
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: A-ci, C-enhancement, beta-nominated, stable-nominated
