Repository spiral/roadrunner-binary, pull requests merged in 2021-05, with the labels that each got.

#50 fix(log): uniform log levels
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .rr.yaml
  CHANGELOG.md
  internal/container/config.go
  internal/container/config_test.go
  internal/container/plugins.go
Labels: A-docs, A-logs

#52 fix(config): Config `static` section
  .rr.yaml
Labels: A-other

#54 feat(release): release 2.2.1
  CHANGELOG.md
  go.mod
  go.sum
  internal/container/plugins.go
Labels: A-other, Bug: regression bugs, C-enhancement

#55 feat(docs): JSON schemas
  .editorconfig
  schemas/config/1.0.json
  schemas/config/2.0.json
  schemas/config/readme.md
  schemas/readme.md
Labels: A-docs, A-other

#58 ci(lint): сonfig file linting enabled
  .github/workflows/tests.yml
  .rr.yaml
  CHANGELOG.md
  schemas/config/1.0.schema.json
  schemas/config/2.0.schema.json
  schemas/config/readme.md
  schemas/readme.md
Labels: A-ci, A-tests

#59 ci(docker): latest tag publishing
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
Labels: A-ci, A-other
