Repository spiral/roadrunner-binary, pull requests merged in 2021-06, with the labels that each got.

#65 fix(bug): fix issue with not working `informer.Workers` RPC call
  .golangci.yml
  CHANGELOG.md
  go.mod
  go.sum
  internal/cli/workers/command.go
  internal/container/plugins.go
  plugins.go
Labels: B-performance

#66 feat(docker): add dev `Dockerfile.dev` with `PHP8` and `Xdebug` inside
  Dockerfile.dev
  go.mod
  go.sum
Labels: C-enhancement

#67 feat(local dev): better local development environment
  local_dev/.rr-docker.yaml
  local_dev/Dockerfile.local
  local_dev/Makefile
  local_dev/composer.json
  local_dev/docker-compose.yml
  local_dev/psr-worker.php
Labels: C-enhancement

#68 feat(pre-release): 2.3.0-beta.2 pre-release
  CHANGELOG.md
  go.mod
  go.sum
  internal/container/plugins.go
Labels: C-enhancement

#72 feat(release): release `v2.3.0`
  .gitignore
  go.mod
  go.sum
Labels: C-enhancement

#73 feat(pre-release): beta 2.3.1 pre-release
  .rr.yaml
  go.mod
  go.sum
  internal/container/plugins.go
Labels: C-enhancement

#74 pre-release: update RR to `v.2.3.1-beta.3`
  .rr.yaml
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement

#75 feat(pre-release): `v2.3.1-beta.4` pre-release
  .rr.yaml
  CHANGELOG.md
  go.mod
  go.sum
  internal/container/plugins.go
Labels: C-enhancement, beta-nominated

#76 feat(plugin): temporal plugin version update
  CHANGELOG.md
  go.mod
  go.sum
Labels: A-module, beta-nominated

#77 feat(pre-release): update dependencies
  go.mod
  go.sum
Labels: C-enhancement, beta-nominated

#78 feat(pre-release): update RR to RC1
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement, beta-nominated

#80 feat(release): `v2.3.1` release
  go.mod
  go.sum
  internal/cli/workers/command.go
Labels: C-enhancement, stable-nominated
