Repository spiral/roadrunner-binary, pull requests merged in 2021-04, with the labels that each got.

#32 upd(rr.yaml): Add comment to the rpc section
  .rr.yaml
Labels: A-docs

#36 upd(config): Add new option to the .rr.yaml
  .rr.yaml
  CHANGELOG.md
Labels: A-docs

#39 feat(platform): Add support for the linux/arm64 binaries in the releases
  .github/workflows/release.yml
  CHANGELOG.md
Labels: A-ci, C-enhancement, beta-nominated, stable-nominated

#42 fix(env): Do not use any name for the env by default
  internal/cli/root.go
  internal/cli/root_test.go
Labels: Bug: regression bugs

#43 feat(informer): Update informer statistic
  CHANGELOG.md
  go.mod
  go.sum
  internal/cli/workers/command.go
  internal/container/plugins.go
Labels: Bug: regression bugs, C-enhancement

#46 upd(.rr.yaml): add new services to the `.rr.yaml`
  .rr.yaml
Labels: A-other
